name: csv_data_cleaning

on:
  push:
    branches: [main]

  # workflow_level_secrets
  # env:
  #   postgress_user: ${{var.USER}}
  #   postgress_pass: ${{secrets.PASS}}

jobs:
  build:
    runs-on: ubuntu-latest

  # job_level_secrets
  # env:
  #   postgress_user: ${{var.USER}}
  #   postgress_pass: ${{secrets.PASS}}

    steps:
      - uses: actions/checkout@v4
  
      # step_level_secrets
      # env:
      #   postgress_user: ${{var.USER}}
      #   postgress_pass: ${{secrets.PASS}}
  
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
  
      - name: install libraries
        run: pip install -r requirements.txt
  
      - name: run flake8
        run: python flake8 main.py
  
      - name: run pylint
        run: python pylint main.py
  
      - name: run mypy
        run: python mypy main.py
